# Generated by Django 5.2.1 on 2025-06-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('meaning', models.TextField(blank=True, null=True)),
                ('sinonym', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('rus_meaning', models.TextField(blank=True, null=True)),
                ('uzb_latin_meaning', models.TextField(blank=True, null=True)),
                ('uzb_kiril_meaning', models.TextField(blank=True, null=True)),
                ('en_meaning', models.TextField(blank=True, null=True)),
                ('turk_meaning', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Word',
                'verbose_name_plural': 'Words',
                'db_table': 'words',
                'ordering': ['name'],
            },
        ),
    ]
